# Generated by Django 4.2.29 on 2026-09-02 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room_schedules", "0024_event_sensitivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="The datastore's building_code. Blank when it supplies none for this building.",
                        max_length=50,
                        verbose_name="Building code",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "missing_from_source",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically when the datastore stops returning any room in this building.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "estate building",
                "verbose_name_plural": "estate buildings",
                "ordering": ["campus__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "missing_from_source",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically when the datastore stops returning any room on this campus.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "verbose_name": "campus",
                "verbose_name_plural": "campuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lsd_id",
                    models.CharField(
                        editable=False,
                        help_text="ExportRoom.id — the datastore's stable key for this room.",
                        max_length=255,
                        unique=True,
                        verbose_name="Datastore id",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "room_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("bookable", models.BooleanField(db_index=True, default=False)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                ("map_slug", models.CharField(blank=True, default="", max_length=255)),
                (
                    "optime_index",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="EventMap/Optime's own key for this room. Kept as the join path to booking data; indexed because lookup is its only use.",
                        null=True,
                    ),
                ),
                (
                    "av_type_slug",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                (
                    "av_type_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("usages", models.JSONField(blank=True, default=list, editable=False)),
                (
                    "org",
                    models.JSONField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                (
                    "owner_label",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Flattened from the datastore's `org` object so the list can be filtered by owner. Informational.",
                        max_length=255,
                        verbose_name="Owning school / department",
                    ),
                ),
                (
                    "missing_from_source",
                    models.BooleanField(
                        default=False,
                        help_text="Set automatically when the datastore stops returning this room. Kept rather than deleted because something here still points at it.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="estate.building",
                    ),
                ),
            ],
            options={
                "verbose_name": "estate room",
                "verbose_name_plural": "estate rooms",
                "ordering": ["building__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "display_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_link",
                        to="room_schedules.room",
                        verbose_name="Display room",
                    ),
                ),
                (
                    "estate_room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="display_link",
                        to="estate.room",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "room link",
                "ordering": ["estate_room__name"],
            },
        ),
        migrations.CreateModel(
            name="BuildingLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "display_building",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_link",
                        to="room_schedules.building",
                        verbose_name="Display building",
                    ),
                ),
                (
                    "estate_building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="display_links",
                        to="estate.building",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "building link",
                "ordering": ["estate_building__name"],
            },
        ),
        migrations.AddField(
            model_name="building",
            name="campus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buildings",
                to="estate.campus",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["building", "name"], name="estate_room_buildin_ef1ad9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["campus", "name"], name="estate_buil_campus__3bc397_idx"
            ),
        ),
    ]
