# Generated by Django 4.2.29 on 2026-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="code",
        ),
        migrations.RemoveField(
            model_name="room",
            name="av_type_label",
        ),
        migrations.RemoveField(
            model_name="room",
            name="av_type_slug",
        ),
        migrations.RemoveField(
            model_name="room",
            name="bookable",
        ),
        migrations.RemoveField(
            model_name="room",
            name="map_slug",
        ),
        migrations.RemoveField(
            model_name="room",
            name="optime_index",
        ),
        migrations.RemoveField(
            model_name="room",
            name="org",
        ),
        migrations.RemoveField(
            model_name="room",
            name="owner_label",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_type",
        ),
        migrations.RemoveField(
            model_name="room",
            name="usages",
        ),
        migrations.AddField(
            model_name="campus",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The datastore's campus_name_short. Informational; not used to identify the campus.",
                max_length=20,
                verbose_name="Short code",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="active_raw",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=50,
                verbose_name="active (raw)",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="av_type",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="host_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="room",
            name="room_status",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="service_provider",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="support_group",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="support_type",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="usage",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="voip_number",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="VoIP number"
            ),
        ),
        migrations.AlterField(
            model_name="campus",
            name="name",
            field=models.CharField(
                help_text="The datastore's campus_lst — the internal campus name.",
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="lsd_id",
            field=models.CharField(
                editable=False,
                help_text="The datastore's stable key for this room.",
                max_length=255,
                unique=True,
                verbose_name="Datastore id",
            ),
        ),
    ]
