# Generated by Django 4.2.29 on 2026-09-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0002_remove_building_code_remove_room_av_type_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="active_raw",
        ),
        migrations.RemoveField(
            model_name="room",
            name="av_type",
        ),
        migrations.RemoveField(
            model_name="room",
            name="host_key",
        ),
        migrations.RemoveField(
            model_name="room",
            name="support_group",
        ),
        migrations.RemoveField(
            model_name="room",
            name="usage",
        ),
        migrations.AddField(
            model_name="room",
            name="active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Open today, by the datastore's start and end dates for this room. Screens in an inactive room are flagged.",
                verbose_name="open today",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="building_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Estates' code for the building this room is in. Not unique to one building, and blank where Estates does not own it.",
                max_length=20,
                verbose_name="Estates building code",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="optime_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The timetabling system's id for this room, where it has one.",
                null=True,
                verbose_name="Optime index",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="public_campus",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The datastore's public campus grouping, as sent for this room. Informational; the campus is the building's.",
                max_length=200,
            ),
        ),
    ]
