# Generated by Django 4.2.29 on 2026-09-30 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estate", "0003_signage_feed"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "buildings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Every room in these buildings, including rooms added later.",
                        related_name="location_groups",
                        to="estate.building",
                    ),
                ),
                (
                    "campuses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Every building and room on these campuses.",
                        related_name="location_groups",
                        to="estate.campus",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [("access_all_locations", "Can see all locations")],
            },
        ),
        migrations.CreateModel(
            name="LocationGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="estate.locationgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "location group membership",
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddField(
            model_name="locationgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="location_groups",
                through="estate.LocationGroupMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="locationgroup",
            name="rooms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Just these rooms.",
                related_name="location_groups",
                to="estate.room",
            ),
        ),
    ]
