# Generated by Django 4.2.29 on 2026-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0023_alter_playlist_description_alter_schedule_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="plays_everything",
        ),
    ]
