# Generated by Django 4.2.29 on 2026-05-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screens", "0024_remove_playlist_plays_everything"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="screens.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "team")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                through="screens.TeamMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="teams",
            field=models.ManyToManyField(related_name="playlists", to="screens.team"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="teams",
            field=models.ManyToManyField(related_name="schedules", to="screens.team"),
        ),
        migrations.AddField(
            model_name="screen",
            name="teams",
            field=models.ManyToManyField(related_name="screens", to="screens.team"),
        ),
        migrations.AddField(
            model_name="source",
            name="teams",
            field=models.ManyToManyField(related_name="sources", to="screens.team"),
        ),
    ]
