# Generated by Django 4.2.29 on 2026-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0026_seed_default_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"verbose_name": "content", "verbose_name_plural": "content"},
        ),
        migrations.AlterField(
            model_name="source",
            name="playlists",
            field=models.ManyToManyField(
                blank=True,
                help_text="All content that would be played by these playlists will be included in this one too.",
                related_name="sources",
                through="screens.PlaylistEntry",
                to="screens.playlist",
            ),
        ),
    ]
