# Generated by Django 4.2.29 on 2026-05-29 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0027_source_content_rename"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screen",
            options={
                "permissions": [
                    (
                        "change_ticker_text",
                        "Can change ticker text and style on screens",
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_background_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CSS color. Leave blank to use preset.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_background_opacity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Background opacity 0-100 (%). Leave blank to use preset. Text stays fully opaque regardless.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_font_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CSS color (e.g. #ffffff). Leave blank to use preset.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_font_size_px",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Override preset font size (px). Leave blank to use preset.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_layout",
            field=models.CharField(
                choices=[
                    ("OVERLAY", "Overlay (cover bottom of content)"),
                    ("SHRINK", "Shrink content to fit above ticker"),
                ],
                default="OVERLAY",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_scroll_speed_px_sec",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Override preset scroll speed (px/sec). Leave blank to use preset.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_style_preset",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic news ticker"),
                    ("MINIMAL", "Minimal subtle bar"),
                    ("BOLD", "Bold marquee"),
                ],
                default="CLASSIC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="ticker_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
