# Generated by Django 4.2.29 on 2026-06-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "screens",
            "0028_alter_screen_options_screen_ticker_background_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="interspersed_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screens.source",
                verbose_name="Interspersed Content",
            ),
        ),
        migrations.AlterField(
            model_name="playlistentry",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="screens.source",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="interspersed_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Optional (you probably want an event schedule here)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screens.source",
                verbose_name="Interspersed Content",
            ),
        ),
    ]
