# Generated by Django 4.2.29 on 2026-06-05 10:53

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0029_alter_playlist_interspersed_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="interspersed_source",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="A single piece of content shown between each regular entry (e.g. a logo or ad between every slide). It is not part of the normal rotation. Leave blank for none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="screens.source",
                verbose_name="Interspersed Content",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content from these parent playlists is added to this one. This playlist's own entries play first, then inherited content follows.",
                related_name="children",
                through="screens.PlaylistRelation",
                to="screens.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlistentry",
            name="number",
            field=models.IntegerField(
                help_text="Play order within this playlist: lower numbers play first. Duplicate numbers are allowed but their relative order is then undefined."
            ),
        ),
        migrations.AlterField(
            model_name="playlistrelation",
            name="inheriting_list",
            field=models.ForeignKey(
                help_text="The child playlist that receives the parent's content.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents_list",
                to="screens.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="playlistrelation",
            name="super_list",
            field=models.ForeignKey(
                help_text="The parent playlist to inherit content from.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children_list",
                to="screens.playlist",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="default_playlist",
            field=models.ForeignKey(
                help_text="Fallback playlist shown whenever no rule currently matches the date and time.",
                on_delete=django.db.models.deletion.PROTECT,
                to="screens.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Marks the schedule used app-wide when a screen has none assigned. Only one schedule should be the default.",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="end_time",
            field=models.TimeField(
                help_text="Time of day the rule's playlist stops being active. Set to 00:00 (midnight) to mean end of day."
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="occurrences",
            field=recurrence.fields.RecurrenceField(
                help_text="Which days the rule fires, as a repeating pattern (e.g. every Monday and Wednesday). The rule only applies on matching days."
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="playlist",
            field=models.ForeignKey(
                help_text="The playlist shown while this rule is active.",
                on_delete=django.db.models.deletion.CASCADE,
                to="screens.playlist",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="priority",
            field=models.IntegerField(
                help_text="When several rules match the same moment, the one with the LOWEST priority number wins (lower number = higher precedence). If none match, the schedule's default playlist is shown."
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="start_time",
            field=models.TimeField(
                help_text="Time of day the rule's playlist becomes active (on matching days)."
            ),
        ),
        migrations.AlterField(
            model_name="schedulerule",
            name="starts",
            field=models.DateField(
                help_text="The rule is inactive until this date. Use it to schedule a rule to begin in the future."
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="ip",
            field=models.GenericIPAddressField(
                help_text="The device's network address (IPv4 or IPv6). The system uses it to recognise this physical screen."
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="schedule",
            field=models.ForeignKey(
                help_text="The schedule that decides which playlist this screen shows at any given date and time.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="screens.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="ticker_layout",
            field=models.CharField(
                choices=[
                    ("OVERLAY", "Overlay (cover bottom of content)"),
                    ("SHRINK", "Shrink content to fit above ticker"),
                ],
                default="OVERLAY",
                help_text="Overlay draws the ticker on top of the content. Shrink scales the content down to make room for the ticker below it.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="ticker_style_preset",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic news ticker"),
                    ("MINIMAL", "Minimal subtle bar"),
                    ("BOLD", "Bold marquee"),
                ],
                default="CLASSIC",
                help_text="Visual preset for the ticker. Individual colors, sizes and speed can be overridden by the fields below.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Content stops playing after this date/time and is later cleaned up automatically. Leave blank for no end limit.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.TextField(
                help_text="A label for this content, shown to operators in lists and playlists."
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("IMG", "Image"), ("VID", "Video"), ("FRM", "Website")],
                help_text="Image and Video play a file you upload. Website embeds a live web page (URL) as an iframe.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="valid_from",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Content is hidden from playback before this date/time. Leave blank for no start limit.",
                null=True,
            ),
        ),
    ]
