# Generated by Django 4.2.29 on 2026-08-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0030_alter_playlist_interspersed_source_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="screen",
            options={
                "permissions": [
                    (
                        "change_ticker_text",
                        "Can change ticker text and style on screens",
                    ),
                    (
                        "change_ticker_settings",
                        "Can turn the ticker on and choose its layout on screens",
                    ),
                ]
            },
        ),
    ]
