# Generated by Django 4.2.29 on 2026-08-10 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Playlist.name is an unbounded TextField, but the admin writes str(obj) into
# django_admin_log.object_repr, a varchar(200). See KNOWN_ISSUES.md.
NAME_PREFIX = "Interspersed: "
NAME_MAX_LENGTH = 150

# The old serialiser emitted interspersed items with no duration at all, and the
# player fell back to 10 seconds. Written explicitly so converted playlists keep
# their existing timing even if Playlist.default_duration's default changes.
LEGACY_INTERSPERSED_DURATION = 10

DESCRIPTION = (
    "Created automatically when interspersed content became playlist-based. "
    "It holds the single item this playlist or screen used to intersperse. "
    "Rename it, add more items, or point the owner at a different playlist."
)


def _converted_name(source):
    return (NAME_PREFIX + source.name)[:NAME_MAX_LENGTH]


def convert_interspersed_sources(apps, schema_editor):
    """Turn every interspersed Source into a one-entry Playlist.

    Deduped per Source: one new playlist however many playlists and screens
    referenced it, with teams unioned across all of them so nobody loses sight
    of content they could previously see.

    Idempotent. MariaDB has no transactional DDL, so a failure part-way through
    leaves the new columns in place and the data half-copied; re-running must
    reuse what the first attempt created rather than duplicate it.
    """
    Playlist = apps.get_model("screens", "Playlist")
    PlaylistEntry = apps.get_model("screens", "PlaylistEntry")
    Screen = apps.get_model("screens", "Screen")
    Team = apps.get_model("screens", "Team")

    def owners_of(model, **extra):
        return list(model.objects.filter(interspersed_source__isnull=False, **extra)
                                 .select_related("interspersed_source"))

    # Anything already carrying both fields was converted by an earlier run.
    already_done = (owners_of(Playlist, interspersed_playlist__isnull=False)
                    + owners_of(Screen, interspersed_playlist__isnull=False))
    todo = (owners_of(Playlist, interspersed_playlist__isnull=True)
            + owners_of(Screen, interspersed_playlist__isnull=True))
    if not todo:
        return

    # Teams are unioned across every referrer, including ones a previous run
    # already handled, so a resumed migration still widens visibility correctly.
    team_ids = {}
    for owner in already_done + todo:
        team_ids.setdefault(owner.interspersed_source_id, set()).update(
            owner.teams.values_list("id", flat=True))

    converted = {owner.interspersed_source_id: owner.interspersed_playlist
                 for owner in already_done}

    default_team = None
    for owner in todo:
        source = owner.interspersed_source
        playlist = converted.get(source.id)
        if playlist is None:
            playlist = Playlist.objects.create(
                name=_converted_name(source),
                description=DESCRIPTION,
                default_duration=LEGACY_INTERSPERSED_DURATION,
            )
            PlaylistEntry.objects.create(
                playlist=playlist, source=source, number=10, duration=None)

            teams = team_ids.get(source.id) or set(source.teams.values_list("id", flat=True))
            if not teams:
                # Screens auto-created for unknown IPs have no teams, and a
                # team-less playlist is invisible to every non-superuser and
                # cannot be fixed through the admin, which hides the teams
                # widget from them while Playlist.clean() demands one.
                if default_team is None:
                    default_team, _ = Team.objects.get_or_create(name="Default")
                teams = {default_team.id}
            playlist.teams.add(*teams)

            converted[source.id] = playlist

        owner.interspersed_playlist = playlist
        owner.interspersed_rate = 1  # the old behaviour was exactly "after every item"
        owner.save()  # plain save so Playlist.last_updated's auto_now republishes


def restore_interspersed_sources(apps, schema_editor):
    """Point the old FK back at the interspersed playlist's first item.

    Lossy: a playlist that gained further items keeps only its first, and the
    auto-created playlists are deliberately left behind — by now they may carry
    edits or relations, and there is no reliable way to tell which were ours.
    Rolling back and re-applying therefore creates duplicates.
    """
    Playlist = apps.get_model("screens", "Playlist")
    Screen = apps.get_model("screens", "Screen")

    for model in (Playlist, Screen):
        for owner in model.objects.filter(interspersed_playlist__isnull=False):
            entry = (owner.interspersed_playlist.playlistentry_set
                     .order_by("number", "id").first())
            owner.interspersed_source_id = entry.source_id if entry else None
            owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0031_alter_screen_options"),
    ]

    # Ordered add -> convert -> remove, in one file, so migrate can never land
    # in a state where the old columns are gone and the conversion never ran.
    operations = [
        migrations.AddField(
            model_name="playlist",
            name="interspersed_playlist",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="A playlist whose items are mixed into this one (e.g. a logo or standing message). Its items are not part of the normal rotation. Leave blank for none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interspersed_into",
                to="screens.playlist",
                verbose_name="Interspersed playlist",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="interspersed_rate",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many of this playlist's own items play before one interspersed item. 1 shows an interspersed item after every entry.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Interspersed rate",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="interspersed_last_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="interspersed_playlist",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="A playlist mixed into whatever this screen is showing, whichever playlist that is (e.g. an event schedule or room sign). Leave blank for none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interspersed_into_screens",
                to="screens.playlist",
                verbose_name="Interspersed playlist",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="interspersed_rate",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many items play before one interspersed item. 1 shows an interspersed item after every entry.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Interspersed rate",
            ),
        ),
        migrations.RunPython(
            convert_interspersed_sources, restore_interspersed_sources),
        migrations.RemoveField(
            model_name="playlist",
            name="interspersed_source",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="interspersed_source",
        ),
    ]
