# Generated by Django 4.2.29 on 2026-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0032_interspersed_playlists"),
    ]

    # Existing rows get the migrate-time timestamp (the schema editor's
    # effective default for an auto_now DateTimeField), so every screen
    # republishes once on the deploy that applies this. 0032 has not shipped
    # either and does the same in the same pass, so it costs nothing extra.
    #
    # makemigrations also proposed an AlterField on source.file here, which was
    # removed by hand: Source.file's help_text was an f-string over the
    # per-deployment MAX_IMG_WIDTH/MAX_IMG_HEIGHT, so no value was correct in
    # migration state. That is fixed at source in 0034 -- the dimensions moved to
    # the form layer -- so the field is now ordinary and safe to migrate.
    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="interspersed_last_updated",
        ),
        migrations.AddField(
            model_name="screen",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
