# Generated by Django 4.2.29 on 2026-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0032_interspersed_playlists"),
    ]

    # Existing rows get the migrate-time timestamp (the schema editor's
    # effective default for an auto_now DateTimeField), so every screen
    # republishes once on the deploy that applies this. 0032 has not shipped
    # either and does the same in the same pass, so it costs nothing extra.
    #
    # makemigrations also proposed an AlterField on source.file here. That is
    # the phantom diff in KNOWN_ISSUES.md #11 -- Source.file's help_text is an
    # f-string over MAX_IMG_WIDTH/MAX_IMG_HEIGHT, which are per-deployment, so
    # no value is correct in migration state. It has been removed by hand;
    # do not let it back in.
    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="interspersed_last_updated",
        ),
        migrations.AddField(
            model_name="screen",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
