# Generated by Django 4.2.29 on 2026-08-26 16:27

from django.db import migrations, models
import recurrence.fields
import screens.models.source


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0033_screen_last_updated"),
    ]

    # Retires the two drifts that made `makemigrations --check` useless as a CI
    # guard. `source.file`'s help_text used to be an f-string over
    # MAX_IMG_WIDTH/MAX_IMG_HEIGHT, so it varied per deployment and no recorded
    # value could ever be right; the dimensions now live in
    # `screens.models.source.file_help_text()`, applied by the admin form at
    # render time. Both strings below are static, so neither field should need
    # another AlterField unless someone edits the text on purpose.
    # `advertising/tests/test_migration_state.py` fails if that regresses.
    operations = [
        migrations.AlterField(
            model_name="schedulerule",
            name="occurrences",
            field=recurrence.fields.RecurrenceField(
                help_text="Which days the rule fires, as a repeating pattern (e.g. every Monday and Wednesday). The rule only applies on matching days. Pick a frequency and then the days it applies to — a pattern with nothing chosen doesn't say when to run and won't save. In the monthly grid, the four cells after 31 are counted back from the end of the month, so −1 is the last day whether that's the 28th, 29th, 30th or 31st."
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="videos must be mp4",
                null=True,
                upload_to=screens.models.source.get_file_path,
            ),
        ),
    ]
