# Generated by Django 4.2.29 on 2026-08-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("screens", "0034_alter_schedulerule_occurrences_alter_source_file"),
    ]

    # Backs the accent-colour picker in the sidebar user menu. One row per user,
    # created on first choice — absence means "default palette", so no data
    # migration seeds anything here.
    #
    # `accent` carries no `choices=`: they would be recorded in migration state,
    # and every palette added to or retired from `screens.accents.ACCENTS` would
    # then demand an AlterField for a purely cosmetic value. The default below
    # is the literal `screens.accents.DEFAULT_ACCENT` resolved at makemigrations
    # time, which is safe precisely because it is a static constant and not a
    # setting — see the CLAUDE.md rule about settings reaching field definitions.
    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accent", models.CharField(default="graphite", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
