# Generated by Django 4.2.29 on 2026-08-31 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("screens", "0035_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="last_ping_attempt",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="screen",
            name="last_ping_ok",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="ScreenStatusEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("attention", "Needs attention"),
                            ("offline", "Offline"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ping_only", "Responds to ping but is not reporting"),
                            ("recently_lost", "Stopped reporting recently"),
                            ("no_response", "No contact and no ping response"),
                            ("no_contact", "No contact"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(db_index=True)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="screens.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "screen status change",
                "verbose_name_plural": "screen status changes",
                "ordering": ("-at", "-pk"),
            },
        ),
    ]
