# Generated by Django 4.2.29 on 2026-09-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0001_initial"),
        ("screens", "0036_screen_last_ping_attempt_screen_last_ping_ok_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="room",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Where this screen physically is, from the estate directory. Leave blank for a screen that is not in a catalogued room.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screens",
                to="estate.room",
            ),
        ),
    ]
