# Generated by Django 4.2.29 on 2026-10-08 15:04

from django.db import migrations, models
import django.db.models.deletion


def backfill_building(apps, schema_editor):
    """Every screen with a room takes its room's building.

    A queryset update, not save(): the historical model has no custom save(),
    and a full save would bump last_updated and restart every device's
    rotation for a change the player never sees.
    """
    Screen = apps.get_model("screens", "Screen")
    Room = apps.get_model("estate", "Room")
    Screen.objects.filter(room__isnull=False).update(building=models.Subquery(
        Room.objects.filter(pk=models.OuterRef("room")).values("building")[:1]))


class Migration(migrations.Migration):

    dependencies = [
        ("estate", "0005_all_locations_group"),
        ("screens", "0037_screen_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="building",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The building this screen is in. Set from the room when there is one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screens",
                to="estate.building",
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="room",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Where this screen physically is, from the estate directory. Leave blank for a screen in the building but not in a catalogued room, such as a foyer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screens",
                to="estate.room",
            ),
        ),
        # Reversing drops the column, so there is nothing to undo.
        migrations.RunPython(backfill_building, migrations.RunPython.noop),
    ]
