# Generated by Django 4.2.29 on 2026-07-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpDocsAccess",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "help documentation access",
                "verbose_name_plural": "help documentation access",
                "permissions": [
                    ("view_technical_docs", "Can view technical help documentation")
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
